name: 'Create a versioning branch'
description: 'Create a version branch to include additional versioning resources and commits.'
inputs:
  github-token:
    description: >-
      The GitHub token to authorize actions on behalf of users.
    required: true
  base-branch:
    description: >-
      The base branch that a versioning branch will be based.
    required: false
  name-prefix:
    description: >-
      The name prefix to include in the new branch name.
      The new branch name format is: <prefix><version>. Example: Rel_branchv1.0.0-rc.1
      The version will be retrieved from the base-branch, bumped according to the version-level.
    required: false
    default: rel_
  version-level:
    description: >-
      The level of the semver version.
      Accepted inputs: major, minor, patch, and prerelease.
    required: true
  pre-id:
    description: >-
      A valid semver pre-release identifier. Used in command: npm version --preid=<pre-id>
      If specified, the versioning behavior will become 'premajor', 'preminor', 'prepatch', and 'prerelease'.
    required: false
  custom-version:
    description: >-
      The custom version to bump to. If specified, it will be used as the version.
      It needs to be a valid semver format.
    required: false
  pr-number:
    description: >-
      The pull request number for info retrieval uses. If present, the information will be returned
      in the action output, and no new branch will be created as opposed to creating a new branch by
      default without the pr-number.
    required: false
outputs:
  base-branch:
    description: The branch that a versioning branch is based.
  base-version:
    description: The version found in the base branch.
  head-branch:
    description: The versioning branch.
  head-version:
    description: The version tag used for the versioning branch.
  is-prerelease:
    description: A boolean indicator for whether the version is considered as a prerelease or not.
runs:
  using: 'node12'
  main: 'dist/bin/index.js'
